Main svc
RifatSuleymanov/java-explore-with-me pull request #2
Opened 2024-02-27 07:29 UTC by RifatSuleymanov

2024-02-28 04:23 UTC, sergeymamonov requested changes
Не оставляйте закомментированного кода в проекте.

2024-02-28 04:23 UTC, sergeymamonov commented on main-service/pom.xml
> +<!--    <packaging>pom</packaging>-->
Не нужно оставлять закомментированного кода.

2024-02-28 04:23 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/dto/category/CategoryDto.java
> +@Setter
У неизменяемых сущностей dto не может быть сеттеров.

2024-02-28 04:23 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/dto/category/CategoryDto.java
> +import lombok.*;
Лучше не использовать импорт через *, так как это может приводить к конфликтам импорта из разных пакетов. Если это выполняется автоматически идеей, то лучше отключить wildcard import https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcards-for-class

2024-02-28 04:23 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/mapper/RequestMapper.java
> +    @Mapping(source = "event.id", target = "event")
Думаю, что вернее тогда было бы называть поле не event, а eventId, так как в этом поле лежит не сама сущность event, а лишь айдишник.

2024-02-28 04:23 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/model/AdminState.java
> +public enum AdminState {
Не вижу, чтобы перечисление где-то использовалось.

2024-02-28 04:23 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/model/UserState.java
> +public enum UserState {
Не вижу, чтобы перечисление где-то использовалось.

2024-02-28 04:23 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/service/impl/CompilationServiceImpl.java
> +        Pageable pageable = PageRequest.of(pageNum, Math.toIntExact(size));
Где-то эта конструкция вызывается в контроллере, а где-то в сервисе. Лучше сделать единообразно.

2024-02-28 04:23 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +        if (states == null & rangeStart == null & rangeEnd == null) {
Есть разница в операторах между & и &&. Здесь нужный оператор выбран?

2024-02-28 04:23 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +        List<EventState> stateList = states
Может быть NPE.

2024-02-28 04:23 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +        if (eventFromDb.getState().equals(EventState.CANCELED) || eventFromDb.getState().equals(EventState.PENDING)) {
Метод equals безопасно вызывать у константы или у значения, которое гарантированно не равно null. Потому что если значение, у которого вызывается метод equals будет равно null, то получим NPE. Проверьте во всем коде, как вызывается метод equals.

2024-02-28 04:23 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/service/EventService.java
> +    List<EventShortDto> getAllEventsByPublic(String text,
Не делают методы с таким большим количеством аргументов. Легко ошибиться в порядке. Если потребуется добавить новый аргумент, то нужно менять во всех местах, где вызывается этот метод. Поэтому делают класс, куда собирают все аргументы. И передают в метод только один экземпляр этого класса. Если потребуется добавить или удалить поле, то изменения в классе не сломают сигнатуру метода. Но это улучшение опциональное, не настаиваю на его выполнении.

2024-02-28 04:23 UTC, sergeymamonov commented on main-service/src/main/resources/schema.sql
> +/*
Комментированный код?

2024-02-28 04:23 UTC, sergeymamonov commented on stats/pom.xml
> +<!--    <version>0.0.1-SNAPSHOT</version>-->
Комментированный код?

2024-02-28 07:31 UTC, RifatSuleymanov commented on main-service/pom.xml
> +<!--    <packaging>pom</packaging>-->
++

2024-02-28 07:31 UTC, RifatSuleymanov commented on stats/pom.xml
> +<!--    <version>0.0.1-SNAPSHOT</version>-->
+++

2024-02-28 07:31 UTC, RifatSuleymanov commented on main-service/src/main/resources/schema.sql
> +/*
++

2024-02-28 07:37 UTC, RifatSuleymanov commented on main-service/src/main/java/ru/practicum/ewm/dto/category/CategoryDto.java
> +import lombok.*;
++

2024-02-28 07:38 UTC, RifatSuleymanov commented on main-service/src/main/java/ru/practicum/ewm/mapper/RequestMapper.java
> +    @Mapping(source = "event.id", target = "event")
++

2024-02-28 07:38 UTC, RifatSuleymanov commented on main-service/src/main/java/ru/practicum/ewm/model/AdminState.java
> +public enum AdminState {
++

2024-02-28 07:38 UTC, RifatSuleymanov commented on main-service/src/main/java/ru/practicum/ewm/model/UserState.java
> +public enum UserState {
+++

2024-02-28 07:40 UTC, RifatSuleymanov commented on main-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +        if (states == null & rangeStart == null & rangeEnd == null) {
++

2024-02-28 08:28 UTC, RifatSuleymanov commented on main-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +        List<EventState> stateList = states
вроде бы понял и исправил но полностью не уверен в правильности

2024-02-28 08:34 UTC, RifatSuleymanov commented on main-service/src/main/java/ru/practicum/ewm/service/EventService.java
> +    List<EventShortDto> getAllEventsByPublic(String text,
+++

2024-02-28 12:32 UTC, RifatSuleymanov commented on main-service/src/main/java/ru/practicum/ewm/dto/category/CategoryDto.java
> +@Setter
++

2024-02-28 12:39 UTC, RifatSuleymanov commented on main-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +        if (eventFromDb.getState().equals(EventState.CANCELED) || eventFromDb.getState().equals(EventState.PENDING)) {
+++

2024-02-28 12:46 UTC, RifatSuleymanov commented on main-service/src/main/java/ru/practicum/ewm/service/impl/CompilationServiceImpl.java
> +        Pageable pageable = PageRequest.of(pageNum, Math.toIntExact(size));
+++

2024-02-29 04:48 UTC, RifatSuleymanov commented on main-service/src/main/java/ru/practicum/ewm/mapper/RequestMapper.java
> +    @Mapping(source = "event.id", target = "event")
сделал как описано в спеке

2024-02-29 19:18 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/dto/category/CategoryDto.java
> +@Setter
Это касается всех классов dto.

2024-02-29 19:18 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/dto/category/CategoryDto.java
> +import lombok.*;
Посмотрите поиском по всему проекту .*

2024-02-29 19:21 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/service/impl/CompilationServiceImpl.java
> +        Pageable pageable = PageRequest.of(pageNum, Math.toIntExact(size));
Я бы лучше разместил в сервисе. В сервисе больше пространства для маневров, можно и валидацию добавить и логику. А в контроллере лучше ограничиться в передачи входящего запроса в сервис. Но не настаиваю в данном случае.

2024-02-29 19:26 UTC, sergeymamonov commented on main-service/src/main/java/ru/practicum/ewm/service/impl/EventServiceImpl.java
> +        if (eventFromDb.getState().equals(EventState.CANCELED) || eventFromDb.getState().equals(EventState.PENDING)) {
Можно посмотреть поиском по проекту .equals( и сделать лучше.

2024-02-29 19:26 UTC, sergeymamonov approved these changes

2024-03-11 11:22 UTC, merged